# ==========================================
# APPLICATION
# ==========================================
spring.application.name=ecommerce-api
server.port=8081

# ==========================================
# DATABASE (MySQL via WAMP)
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=" "
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# JWT CONFIGURATION
# ==========================================
jwt.secret=ecommerce-secret-key-must-be-very-long-for-security
jwt.expiration=86400000
